name: Backend Code Check

on:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  type-check:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: "**/requirements.txt"

      - name: Install backend dependencies
        working-directory: backend
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          working-directory: backend

  lint:
    runs-on: ubuntu-latest
    needs: type-check
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: "**/requirements.txt"

      - name: Install backend dependencies
        working-directory: backend
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          src: "./backend"
