name: Backend Code Format

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to format'
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Get PR branch
        id: get_head_ref
        run: |
          head_ref_name=$(gh pr view ${{ github.event.inputs.pr_number }} --json headRefName -q .headRefName)
          echo "head_ref=$head_ref_name" >> $GITHUB_OUTPUT


      - name: checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ steps.get_head_ref.outputs.head_ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: "**/requirements.txt"
      
      - name: Install backend dependencies
        working-directory: backend
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          src: "./backend"
          args: "format"
      
      - name: Commit & Push changes
        working-directory: backend
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: auto format by CI"
          git push